module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Direct aliases for component compatibility
        primary: 'var(--brand)',
        secondary: 'var(--secondary)',
        surface: 'var(--s0)',
        card: 'var(--s1)',
        danger: '#EF4444',
        border: 'var(--s3)',
        voro: {
          primary: 'var(--voro-primary)',
          'primary-light': 'var(--voro-primary-light)',
          'primary-dark': 'var(--voro-primary-dark)',
          secondary: 'var(--voro-secondary)',
          'secondary-light': '#34D399',
          accent: 'var(--voro-accent)',
          danger: 'var(--voro-danger)',
          info: 'var(--voro-info)',
          pink: '#EC4899',
          orange: '#F97316',
          surface: 'var(--voro-surface)',
          card: 'var(--voro-card)',
          border: 'var(--voro-border)',
          elevated: 'var(--voro-elevated)',
        }
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
        display: ['Playfair Display', 'serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        condensed: ['Barlow Condensed', 'Inter', 'sans-serif'],
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'expo-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'expo-in': 'cubic-bezier(0.7, 0, 0.84, 0)',
        'silk': 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'snap': 'cubic-bezier(0.35, 0, 0.1, 1)',
        'back': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'spin-slow': 'spin-slow 12s linear infinite',
        'spin-reverse': 'spin-reverse 8s linear infinite',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-right': 'slideRight 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'pulse-slow': 'pulse 3s infinite',
        'bounce-soft': 'bounceSoft 0.6s ease-out',
        'fill-bar': 'fillBar 0.8s ease-out',
        'count-up': 'countUp 1s ease-out',
        'glow': 'glow 2s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s infinite',
        'glitch': 'glitch 0.4s cubic-bezier(.25,.46,.45,.94) both infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: 0 }, '100%': { opacity: 1 } },
        'spin-slow': { 'from': { transform: 'rotate(0deg)' }, 'to': { transform: 'rotate(360deg)' } },
        'spin-reverse': { 'from': { transform: 'rotate(360deg)' }, 'to': { transform: 'rotate(0deg)' } },
        slideUp: { '0%': { opacity: 0, transform: 'translateY(12px)' }, '100%': { opacity: 1, transform: 'translateY(0)' } },
        slideRight: { '0%': { opacity: 0, transform: 'translateX(-12px)' }, '100%': { opacity: 1, transform: 'translateX(0)' } },
        scaleIn: { '0%': { opacity: 0, transform: 'scale(0.95)' }, '100%': { opacity: 1, transform: 'scale(1)' } },
        bounceSoft: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        fillBar: { '0%': { width: '0%' }, '100%': { width: 'var(--target-width)' } },
        glow: { '0%,100%': { boxShadow: '0 0 5px #7C3AED' }, '50%': { boxShadow: '0 0 20px #7C3AED, 0 0 40px #7C3AED55' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        glitch: {
          '0%': { transform: 'translate(0)' },
          '20%': { transform: 'translate(-2px, 2px)' },
          '40%': { transform: 'translate(-2px, -2px)' },
          '60%': { transform: 'translate(2px, 2px)' },
          '80%': { transform: 'translate(2px, -2px)' },
          '100%': { transform: 'translate(0)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-voro': 'linear-gradient(135deg, #7C3AED 0%, #10B981 100%)',
        'gradient-fire': 'linear-gradient(135deg, #F97316 0%, #EF4444 100%)',
        'shimmer-gradient': 'linear-gradient(90deg, transparent, rgba(255,255,255,0.08), transparent)',
      },
    }
  },
  plugins: [require('@tailwindcss/forms')]
}
